name: "EFZ1602"
description: "Fluid, responsive blog theme for Jekyll"

author: "John Doge"

url: "http://efz1602.net"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
