name: "作业中心"
description: "小二班作业发布站"

author: "严恺诚Kyle"

banner_title: "即将重制！"
banner_text: "2020冬季，敬请期待。"

# url: "https://efz1602.github.io"
baseurl: "/"

markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  syntax_highlighter: rouge
