name: "Homework Center"
description: "EFZ1602"

author: "Kaicheng Yan"

url: "http://efz1602.net"
baseurl: "http://efz1602.net"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
