name: "作业中心"
description: "小二班作业发布站"

author: "严恺诚Kyle"

url: "https://efz1602.github.io"
baseurl: "https://efz1602.github.io"

markdown: kramdown
permalink: :year/:month/:title.html
kramdown:
  input: GFM
  syntax_highlighter: rouge
