name: "Homework Center"
description: "H.W. Center for EFZ1602"

author: "Kyle"

url: "http://www.hwcenter.tk"
baseurl: "http://www.hwcenter.tk"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
