name: "小二班"
description: "EFZ1602"

author: "小二班"

banner_title: "暂待更新。"
banner_text: "咕咕咕，咕咕咕。"

# url: "https://efz1602.github.io"

markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
